# Blimp unique ID
id_num: 2

# sensor board parameters
my_ip: "192.168.0.101"
pi_ip: "192.168.0.52"

im_rows: 240
im_cols: 360
fps: 15
qual: 15

# motor board parameters
k_r:  [0.45, 0., -1.7]
k_p:  [0.45, 0., -1.7]
k_yw: [0.001, 0.001, 0.07]
k_pz: [0.35, 0.001, 0.055]

# extra parameter names
extra_names: ["/vicon/openBlimp1/openBlimp1","/vicon/openBlimp2/openBlimp2",
              "/vicon/tag0/tag0","/vicon/tag1/tag1", "/vicon/tag2/tag2", 
              "/vicon/tag3/tag3", "/vicon/tag4/tag4", "/vicon/tag5/tag5",
              "on_signal"]

extra_sizes: [7,7,7,7,7,7,7,7,1]
extra_types: ["float32","float32","float32","float32","float32",
              "float32","float32","float32","bool"]
