# IP address for the pi and base station on the shared network
my_ip: "192.168.186.99"
pi_ip: "192.168.186.1"

# Blimp unique ID
id_num: 1

# camera parameters
im_rows: 240
im_cols: 360
fps: 20
qual: 25
