# Blimp unique ID
id_num: 1

# sensor board parameters
my_ip: "192.168.0.101"
pi_ip: "192.168.0.51"

im_rows: 240
im_cols: 360
fps: 10
qual: 15

# motor board parameters
k_r:  [0.27, 0., -1.2]
k_p:  [0.27, 0., -1.2]
k_yw: [0.001, 0.001, 0.07]
k_pz: [0.12, 0.001, 0.03]

# extra parameter names
extra_names: ["/vicon/openBlimp1/openBlimp1","/vicon/tag0/tag0","/vicon/fan/fan"]
extra_sizes: [7,7,7]
extra_types: ["float32","float32","float32"]
