# Blimp unique ID
id_num: 2

# sensor board parameters
my_ip: "192.168.0.101"
pi_ip: "192.168.0.52"

im_rows: 240
im_cols: 360
fps: 20
qual: 25

# motor board parameters
k_r:  [0., 0., 0.]
k_p:  [0., 0., 0.]
k_yw: [0., 0., 0.]
k_pz: [0., 0., 0.]

